### ISSUE TITLE
Use system font on canvas

### ISSUE THREAD

**Issue by bertob** [gaphor/gaphor#1921]
The text on the actual canvas seems to be a different font from the regular system font, so it looks a bit off:

![image](https://user-images.githubusercontent.com/1908896/207607198-3c640bda-22b1-493d-8cd4-9722f848a5e4.png)

**Comment by amolenaar** [comment]
Currently Gaphor is using the default `sans` font provided by the system. The default GNOME font is _Cantarell_, right?

I'm not sure if we support that on Windows and macOS at the moment.

**Comment by bertob** [comment]
Ideally the font on the canvas would be the same one that is being used for the rest of the UI, i.e. Cantarell on GNOME, Segoe on Windows, and SF on macOS. Is that not easily possible?

**Comment by amolenaar** [comment]
It was actually easier than expected. Although I had to hard-code the font names, since this part of the code should not rely on the GTK library..

**Comment by danyeaw** [comment]
Thanks, @bertob, for another great suggestion! Closed by #1922.

**Comment by amolenaar** [comment]
@bertob Do you think the default line width is okay, or should we change that a little, while we're at it?

**Comment by bertob** [comment]
What do you mean by line width? Or do you mean line height? On which widgets?

**Comment by amolenaar** [comment]
The thickness of the lines used to draw stuff in the diagrams. In the example above the node element.

**Comment by bertob** [comment]
No, the line width seems fine. What I would change though is the styling of the on-canvas resize handles, the green looks a bit retro :D  

I'd try making them larger, with larger border radii, and maybe just a semi-transparent blue background, no borders. Or alternatively, maybe white with a slight shadow?

**Comment by amolenaar** [comment]
Thanks. It is retro indeed, the style has not changed much since I started this project in 2000.

Currently it's using 4 different colors: green for movable handles, red for connected handles, orange when it's dragged and about to be connected, and blue for unmovable handles. It was basically a copy of what Dia does.

**Comment by amolenaar** [comment]
@bertob Something like this? (at 200%)

![image](https://user-images.githubusercontent.com/96249/207966284-1e9d8ff2-0221-4392-bee4-c01317d95e73.png)

**Comment by bertob** [comment]
Is there a branch I can try? Looks like a promising direction, but it's hard to judge how it feels without actually using it.

**Comment by amolenaar** [comment]
I created a branch [new-handle-style](https://github.com/gaphor/gaphor/tree/new-handle-style).

NB. the handles used to split line segments should still be revamped.

**Comment by bertob** [comment]
Thanks! I tried to build the branch, but I get this error:

```
Installing collected packages: webencodings, trove-classifiers, ptyprocess, msgpack, lockfile, distlib, zipp, urllib3, tomlkit, tomli, shellingham, rapidfuzz, pyrsistent, pycparser, poetry-core, platformdirs, pkginfo, pexpect, packaging, more-itertools, jeepney, idna, html5lib, filelock, crashtest, charset-normalizer, certifi, attrs, virtualenv, requests, jsonschema, jaraco.classes, importlib-metadata, dulwich, cleo, cffi, requests-toolbelt, cryptography, cachecontrol, SecretStorage, keyring, poetry-plugin-export, poetry
Successfully installed SecretStorage attrs cachecontrol certifi cffi charset-normalizer cleo crashtest cryptography distlib dulwich filelock html5lib idna importlib-metadata jaraco.classes jeepney jsonschema keyring lockfile more-itertools msgpack packaging pexpect pkginfo platformdirs poetry poetry-core poetry-plugin-export ptyprocess pycparser pyrsistent rapidfuzz requests requests-toolbelt shellingham tomli tomlkit trove-classifiers urllib3 virtualenv webencodings zipp
Running: ${FLATPAK_DEST}/bin/poetry export --output=requirements.txt
Running: pip3 install --prefix=${FLATPAK_DEST} -r requirements.txt
Ignoring colorama: markers 'python_version >= "3.9" and python_version < "3.12" and sys_platform == "win32"' don't match your environment
Collecting gaphas@ git+https://github.com/gaphor/gaphas.git@new-handle-style
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    gaphas@ git+https://github.com/gaphor/gaphas.git@new-handle-style from git+https://github.com/gaphor/gaphas.git@new-handle-style (from -r requirements.txt (line 28))
Error: module install: Child process exited with code 1
```

**Comment by amolenaar** [comment]
Ouch. I fixed some updates and tried with GNOME Builder. It works for me now. Hopefully it works for you too.

**Comment by bertob** [comment]
Works now! The new handles are a nice improvement, +1 from my side.

Something I noticed while trying them is that the cursor doesn't change depending on whether dragging will move/resize/etc. which seems like a lost opportunity for feedforward. Could we set the cursor to the resize/corner resize/move cursor as appropriate, when hovering over an object?

**Comment by amolenaar** [comment]
> Could we set the cursor to the resize/corner resize/move cursor as appropriate, when hovering over an object?

I'll look into this. It will probably take a bit more effort. It would be a nice improvement indeed.

**Comment by bertob** [comment]
I just noticed trying the branch with the new handles that there are also these small inbetween handles, which still have a border:

![image](https://user-images.githubusercontent.com/1908896/208100437-3583c5c4-5818-406c-88de-1accb2c548b9.png)

**Comment by amolenaar** [comment]
Yup. I've been changing those as well. I've also added the cursor-change-on-hover feature (for the in-between handles too). The changes are done in [Gaphas](https://github.com/gaphor/gaphas), our canvas library.

**Comment by amolenaar** [comment]
@bertob I merged some changes to main. Lines and element handles now look more fancy:

![image](https://user-images.githubusercontent.com/96249/208248014-3be203c9-987b-4e03-9f4c-c9a2216357f6.png)

The mouse cursor also changes on hover.
