### ISSUE TITLE
The upper portion of vertically long height characters missed

### ISSUE THREAD

**Issue by Kimoto-Satoshi** [gaphor/gaphor#2592]
### Describe the bug
The upper portion of vertically long height characters in “Name” and “Comment” are displayed with a lack of upper portion.

### To Reproduce
1. Open the file FreezeIssueModel.gaphor of [IssueLackUpperPortion.zip](https://github.com/gaphor/gaphor/files/12223834/IssueLackUpperPortion.zip)
2. Open the diagram "Interrupt" from package "InterruptStyle"

If possible, add the error report from `≡` (top-right menu) → `Tools` → `Error Reports`.
Gaphor version:         2.19.3
Operating System:       Windows (10)
Display:                GdkWin32Display
Python version:         3.11.4
GTK version:            4.10.3
Adwaita version:        1.3.1
GtkSourceView version:  5.8.0
Cairo version:          1.17.8
Pango version:          1.50.14
PyGObject version:      3.44.1
Pycairo version:        1.23.0
pygit2/libgit2 version: 1.12.2  / 1.6.4

### Expected behavior
The upper portion of vertically long height characters shall be displayed without lacking.

### Screenshots
2023-08-01_10h56_01.png of [IssueLackUpperPortion.zip](https://github.com/gaphor/gaphor/files/12223834/IssueLackUpperPortion.zip)

### OS
- [ ] Linux (Please put in notes the specific distro)
- [ ] macOS
- [x ] Windows

### Version
Version of Gaphor:
3.19.3

**Comment by danyeaw** [comment]
Hi @Kimoto-Satoshi, thank you so much for the bug report!

Here is your screenshot you attached:
![2023-08-01_10h56_01](https://github.com/gaphor/gaphor/assets/10014976/28402ee1-cef4-4f4a-96f7-a5ad09807c9f)

I only have my Linux computer with me, and I'm not able to reproduce this, it might be an upstream bug in GTK with Windows. We just released Gaphor 2.20.0 which uses a newer GTK version, does the problem still exist in this version?

**Comment by Kimoto-Satoshi** [comment]
Hi @danyeaw, 
Thanks for your support. I tried it with version 2.20.0, but it still occurs.
<img width="485" alt="2023-08-09_21h14_01" src="https://github.com/gaphor/gaphor/assets/5249391/63a5ba5d-382c-49e1-ac34-2668723004ab">
